/**
PRACTICA 3
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 11/10/2021
DESCRIPCION: APRENDER A USAR LA FUNCION COUNT() Y HAVING
**/

--CREAR BASE DE DATOS
CREATE DATABASE REFUGIOMASCOTAS
ON PRIMARY
(
NAME = 'REFUGIOMASCOTAS.MDF',
FILENAME = 'C:\TBD2021\U2\REFUGIOMASCOTAS.MDF'
)
LOG ON
(
NAME = 'REFUGIOMASCOTAS.LDF',
FILENAME = 'C:\TBD2021\U2\REFUGIOMASCOTAS.LDF'
);

--PONER EN USO LA BD
USE REFUGIOMASCOTAS;

--CREAR LA TABLA MASCOTAS
CREATE TABLE MASCOTAS
(
ID_MASCOTA INT PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
ESPECIE CHAR(1) NOT NULL CHECK(ESPECIE ='P' OR ESPECIE ='G'),
SEXO CHAR(1) NOT NULL CHECK(SEXO ='M' OR SEXO ='H'),
UBICACION VARCHAR(6) NOT NULL,
ESTADO CHAR(1) NOT NULL CHECK(ESTADO ='A' OR ESTADO ='B')
);

--INSERTAR REGISTROS EN LA TABLA MASCOTAS
INSERT INTO MASCOTAS
VALUES
(1, 'Budy','P','M','E05', 'B'),
(2, 'Pipo','P','M','E02', 'B'),
(3, 'Nuna','P','H','E02', 'A'),
(4, 'Bruts','P','M','E03', 'A'),
(5, 'Americo','G','M','E04', 'A'),
(6, 'Sombra','P','H','E05', 'A'),
(7, 'Avispa','G','H','E06', 'A'),
(8, 'Panda','G','H','E06', 'A'),
(9, 'Pecas','P','M','E07', 'A'),
(10, 'Manchas','P','M','E07', 'B');

--CUANTOS PERROS DE CADA SEXO HAY EN EL REFUGIO
SELECT SEXO,COUNT(SEXO) AS PERROS_VIGENTES FROM MASCOTAS WHERE ESPECIE='P' AND ESTADO='A' GROUP BY SEXO;

--CUANTOS EJEMPLARES CONTIENE ACTUALMENTE CADA JAULA O UBICACION?
SELECT UBICACION, COUNT(UBICACION) AS 'EJEMPLARES' FROM MASCOTAS WHERE ESTADO='A' GROUP BY UBICACION;

--CUANTOS EJEMPLARES DE CADA ESPECIE Y DENTRO DE CADA ESPECIE DE CADA SEXO HAY ACTUALMENTE EN EL CENTRO?
SELECT ESPECIE, SEXO, COUNT(ESPECIE) AS 'TOTAL DE ESPECIE'FROM MASCOTAS WHERE ESTADO='A' GROUP BY ESPECIE, SEXO ORDER BY ESPECIE;

--CUANTOS PERROS DE CADA SEXO HAY EN TOTAL ACTUALMENTE EN EL CENTRO?
SELECT ESPECIE, SEXO, COUNT(ESPECIE) AS 'TOTAL PERROS' FROM MASCOTAS WHERE ESTADO='A' AND ESPECIE='P' GROUP BY ESPECIE, SEXO;

--INSERTAR REGISTROS EN LA TABLA MASCOTAS
INSERT INTO MASCOTAS
VALUES
(11, 'Loki','P','M','E05', 'A'),
(12, 'Zeus','P','M','E05', 'A'),

(13, 'PERRO3','P','H','E06', 'A'),

(14, 'GATO1','G','H','E04', 'A'),
(15, 'GATO2','G','M','E04', 'A'),
(16, 'GATO3','G','H','E04', 'A');

--ACTUALIZAR ESTOS DE LA TABLA MASCOTAS DONDE EL ID DE LA MASCOTA SEA IGUAL A 16
UPDATE MASCOTAS
SET ESTADO = 'B'
WHERE ID_MASCOTA = 16;

--ACTUALIZAR ESTOS DE LA TABLA MASCOTAS DONDE EL ID DE LA MASCOTA SEA IGUAL A 10
UPDATE MASCOTAS
SET UBICACION='E02'
WHERE ID_MASCOTA = 10;

--¿Que ubicaciones del centro de mascotas tienen mas de dos ejemplares?
SELECT UBICACION, count(UBICACION) as EJEMPLARES FROM MASCOTAS WHERE ESTADO = 'A' GROUP BY UBICACION
HAVING count(UBICACION) > 2;

--Muestra los ejemplares cuantos ejemplares tiene cada estatus y de que sexo dentro
--de las ubicaciones E02 , E03 , E06 Y E07
SELECT ESTADO, SEXO, COUNT(ESTADO) AS 'EJEMPLARES' FROM MASCOTAS WHERE UBICACION IN('E02','E03','E06','E07')
GROUP BY ESTADO, SEXO;

--¿Que ubicaciones del centro de mascotas tienen tan solo un ejemplar?
SELECT UBICACION, count(UBICACION) AS EJEMPLARES FROM MASCOTAS WHERE ESTADO = 'A' GROUP BY UBICACION
HAVING count(UBICACION) = 1;

--Construye una consulta que devuelva las ubicaciones del centro de mascotas que
--tiene entre 2 y 3 ejemplares (usa between).
SELECT UBICACION, count(UBICACION) AS EJEMPLARES FROM MASCOTAS WHERE ESTADO = 'A' GROUP BY UBICACION
HAVING count(UBICACION) BETWEEN 2 AND 3;

--Obtenga el numero actual de ejemplares de cada ubicacion del centro de mascotas,
--que tengan dos o mas ejemplares ordenado de mayor a menor por numero de
--ejemplares y en segundo termino por ubicacion.
SELECT UBICACION, COUNT(UBICACION) AS EJEMPLARES FROM MASCOTAS WHERE ESTADO='A' GROUP BY UBICACION
HAVING count(UBICACION) BETWEEN 2 AND 3 ORDER BY EJEMPLARES DESC, UBICACION DESC;