/**
PRACTICA 5
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 13/10/2021
DESCRIPCION: USO DE CONSULTAS COMBINADAS Y TOP
**/

USE Northwind;

/*
1. MOSTRAR LAS ORDENES DE VENTA DE LA ORDEN 10510 A 10570 PROYECTANDO LA SIGUIENTE INFORMACION:
NO. ORDEN, NOMBRE COMPLETO DEL EMPLEADO QUE VENDIO LA ORDEN
*/
SELECT O.OrderID AS [No. Orden], O.OrderDate, E.FirstName+''+E.LastName AS [NOMBRE VENDEDOR]
FROM Orders O
INNER JOIN Employees E ON (E.EmployeeID = O.EmployeeID)
WHERE O.OrderID BETWEEN 10510 AND 10570;

/*
2. MOSTRAR LAS ORDENES DE VENTA DE LA ORDEN 10510 A 10570
PROYECTANDO LA SIGUIENTE INFORMACION: NO. DE ORDEN, FECHA DE ORDEN, NOMBRE COMPLETO DEL EMPLEADO QUE
VENDIO LA ORDEN, EL NOMBRE DE LA COMPAÑIA QUE COMPRO LA ORDEN Y NOMBRE DEL CONTACTO DE DICHA COMPAÑIA
*/
SELECT O.OrderID AS [No. Orden], O.OrderDate, E.FirstName+''+E.LastName AS [NOMBRE VENDEDOR],
C.CompanyName AS [Compa�ia], C.ContactName AS [Contacto]
FROM Orders O
INNER JOIN Employees E ON (E.EmployeeID = O.EmployeeID)
INNER JOIN Customers C ON (C.CustomerID = O.CustomerID)
WHERE O.OrderID BETWEEN 10510 AND 10570;


/*
3- MOSTRAR EL DETALLE DE LAS ORDENES 10250 A LA 10253. MOSTRANDO EL ID DE LA ORDEN, ID DEL PRODUCTO QUE
SE VENDIO, NOMBRE DEL PRODUCTO QUE SE VENDIO, PRECIO AL QUE SE VENDIO, EL NOMBRE DE LA CATEGORIA
A LA QUE PERTENECE EL PRODUCTO
*/
SELECT DO.OrderID, DO.ProductID, P.ProductName, DO.UnitPrice, C.CategoryName
FROM [Order Details] DO
INNER JOIN Products P ON (P.ProductID = DO.ProductID)
INNER JOIN Categories C ON (C.CategoryID = P.CategoryID)
WHERE DO.OrderID BETWEEN 10250 AND 10253;


--CONSULTA COMBINADA CON WHERE
SELECT DO.OrderID, DO.ProductID, P.ProductName, DO.UnitPrice, C.CategoryName
FROM [Order Details] DO, Products P, Categories C
WHERE DO.OrderID BETWEEN 10250 AND 10253
AND
P.ProductID = DO.ProductID
AND
C.CategoryID = P.CategoryID;

--MUESTREN CUANTOS FILAS TIENE LA TABLA DE ORDER DETAILS
SELECT COUNT(*) FROM [Order Details];

--MOSTRAR LAS PRIMERAS 10 ORDENES DE VENTA
SELECT TOP (10) * FROM Orders;

--MOSTRAR LAS ULTIMAS 10 ORDENES DE VENTA
SELECT TOP (10) * FROM Orders ORDER BY OrderID DESC;

--MOSTRAR EL PRIMER 10 PORCIENTO DE LA TABLA ORDERS
SELECT TOP (10) PERCENT * FROM Orders;
