/*
PRACTICA 5
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 24/11/21
DESCRIPCION: CREAR UN PROCEDIMIENTO ALMACENADO PARA LA SUMA DE DOS NUMEROS ENTEROS ENVIADOS COMO PARAMETROS
*/

--PONER EN USO LA BD
USE pubs;

--CREAR EL PROCEDIMIENTO ALMACENADO
CREATE PROC sp_suma (@num1 INT, @num2 INT, @num3 INT OUTPUT) AS
BEGIN	
	IF @NUM1 <0 OR @NUM2<0
	BEGIN 
		PRINT 'ERROR'
		RETURN 1;
	END
	SET @NUM3 = @NUM1 + @NUM2;
	RETURN 0;
END

--EJECUTAR EL PROCEDIMIENTO ALMACENADO
DECLARE @RES INT;
EXEC sp_suma 5, 5, @RES OUTPUT;
SELECT @RES AS [SUMA];