/*
PRACTICA 1
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 23/11/21
DESCRIPCION: Aprender a crear, ejecutar, modificar y borrar procedimientos almacenados
*/

--PONER EN USO LA BD
USE NORTHWIND;

--CREAR EL PROCEDIMIENTO ALMACENADO DE sp_holamundo PARA PINTAR UN HOLA MUNDO 
CREATE PROC sp_holamundo
AS
BEGIN
	PRINT 'HOLA MUNDO .....!!!'
	RETURN
END

--EJECUTAR EL PROCEDIMIENTO ALMACENADO DE sp_holamundo
EXEC sp_holamundo;

--ACTUALIZAR O ALTERAR UN PROCEDIMIENTO ALMACENADO YA EXISTENTE
ALTER PROC sp_holamundo
AS
BEGIN
	PRINT 'HOLA MUNDO :) :) .....!!!'
	RETURN
END

--VISUALIZA EL CODIGO DE UN SP
EXEC sp_helpText sp_holamundo;

--BORRAR EL PROCEDIMIENTO ALMACENADO DE sp_holamundo
DROP PROC sp_holamundo;