/*
PRACTICA 10
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 30/11/21
DESCRIPCION: POR MEDIO DE TRIGGERS CREA UNA BITACORA DE EVENTOS PARA LA BD CAMPONATO DE AJEDREZ,
			 QUE CADA QUE SE REALICE.
*/

--PONER EN USO LA BD
USE CAMPEONATO_DE_AJEDREZ;

--CREACION DEL TRIGGER
CREATE TRIGGER tr_resultados_movtos ON RESULTADOS FOR INSERT, UPDATE, DELETE AS
BEGIN
SET NOCOUNT ON
DECLARE @CANTIDADINSERT INT, @CANTIDADDELE INT, @OPERACION VARCHAR(30);
	IF NOT EXISTS (SELECT * FROM sys.objects WHERE TYPE = 'U' AND NAME = 'BITACORAMOVTOS' )
		CREATE TABLE BITACORAMOVTOS(
		OPERACION VARCHAR(30),
		FECHA DATE,
		APLICACION VARCHAR(300),
		EQUIPO VARCHAR (100),
		USUARIO VARCHAR (50)
		);
	ELSE
		SET @CANTIDADINSERT = (SELECT COUNT(*) FROM INSERTED);
		SET @CANTIDADDELE = (SELECT COUNT(*) FROM DELETED);
		IF @CANTIDADINSERT >0 AND @CANTIDADDELE >0
			SET @OPERACION = 'UPDATE';
		ELSE
			IF @CANTIDADINSERT = 0 AND @CANTIDADDELE > 0
				SET @OPERACION = 'DELETE';
			ELSE
			IF @CANTIDADINSERT > 0 AND @CANTIDADDELE = 0
				SET @OPERACION = 'INSERT';
			ELSE
				SET @OPERACION = 'SIN RENGLONES AFECTADOS';

INSERT INTO BITACORAMOVTOS VALUES (@OPERACION, GETDATE(), APP_NAME(), HOST_NAME(), USER_NAME());
END

--COMPROBAR QUE FUNCIONE
SELECT * FROM RESULTADOS WHERE RES_ID = 3;
UPDATE RESULTADOS
SET RES_PUNTOS = 30
WHERE RES_ID = 3;
SELECT * FROM BITACORAMOVTOS;
SELECT * FROM RESULTADOS WHERE RES_ID = 3;