/*
PRACTICA 3
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 23/11/21
DESCRIPCION: NORTHWIND - CREA UN SP QUE ACTUALICE EL PRECIO DE LOS PRODUCTOS DEL INVENTARIO DE ACUERDO A UN
PORCENTAJE Y UNA CATEGORIA PROPORCIONADO AGREGAR UN DEFAULT AL PORCENTAJE
*/

--PONER EN USO LA BD
USE Northwind;

--CREAR EL PROCEDIMIENTO ALMACENADO
CREATE PROC sp_actualizar_precio_producto_porcentaje (@PORCENTAJE REAL = 0.5, @CATEGORIA INT) AS
BEGIN
	UPDATE Products SET UnitPrice = UnitPrice + (UnitPrice * @PORCENTAJE) WHERE CategoryID = @CATEGORIA;
	RETURN
END

--EJECUTAR EL PROCEDIMIENTO ALMACENADO
EXEC sp_actualizar_precio_producto_porcentaje 0.7, 1;