/*
PRACTICA 9
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 29/11/21
DESCRIPCION: CREA UN TRIGGER QUE CADA QUE SE VENDA UN PRODUCTO DESCUENTE LA CANTIDAD VENDIDA DEL INVENTARIO
*/

--PONER EN USO LA BD
USE Northwind;

--CREAR EL TRIGGER
CREATE TRIGGER tr_orderdetails_insert ON [Order Details] FOR INSERT AS
BEGIN
	DECLARE @PRODUCTOID INT, @CANTIDAD SMALLINT;
	SET @PRODUCTOID = (SELECT ProductID FROM inserted);
	SET @CANTIDAD = (SELECT Quantity FROM inserted);
	UPDATE Products SET UnitsInStock = UnitsInStock - @CANTIDAD WHERE ProductID = @PRODUCTOID;
END

--COMPROBAR QUE FUNCIONA EL DISPARADOR
INSERT INTO [Order Details] VALUES (11093, 1, 23.30, 2, 0);
SELECT * FROM Products WHERE ProductID = 1;
SELECT * FROM [Order Details] WHERE OrderID = 11093;