/*
PRACTICA 15
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 02/12/21
DESCRIPCION: CREA UN DISPARADOR EN LA BD KINDER MUNDO FELIZ PARA CADA QUE SE REGISTREN VOTOS A LOS PARTICIPANTES
CREE UNA TABLA CON LOS PARTICIPANTES QUE TIENEN VOTOS Y LOS VAYA ACUMULANDO. AL FINAL ESTA TABLA TENDRA CADA
PARATICIPANTE CON EL TOTAL DE VOTOS Y LA FECHA Y HORA DEL ULTIMO VOTOACUMULADO.
*/

--PONER EN USO LA BD
USE KINDER_MUNDO_FELIZ;

--CREAR EL DISPARADOR
CREATE TRIGGER tr_votos_participantes ON VOTOS FOR INSERT AS
BEGIN
	IF NOT EXISTS (SELECT * FROM sys.objects a WHERE TYPE = 'U' AND NAME = 'PARTICIPANTES_CON_VOTOS')
		CREATE TABLE PARTICIPANTES_CON_VOTOS(
			CandidatoNombre Varchar(3),
			totalVotos MONEY,
			fechaUltimoVoto DATETIME
		);
	ELSE

	DECLARE @CandidatoId VARCHAR (3), @fechaUltimoVoto DATETIME, @Votos MONEY;

	SELECT
	@CandidatoId = CandidatoId,
	@fechaUltimoVoto = GETDATE(),
	@Votos = Votos
	FROM inserted;

	IF EXISTS (SELECT * FROM PARTICIPANTES_CON_VOTOS WHERE CandidatoNombre = @CandidatoId)
		UPDATE PARTICIPANTES_CON_VOTOS SET
		totalVotos = totalVotos + @Votos,
		fechaUltimoVoto = @fechaUltimoVoto
		WHERE CandidatoNombre = @CandidatoId;
	ELSE

	INSERT INTO PARTICIPANTES_CON_VOTOS VALUES (@CandidatoId, @Votos, @fechaUltimoVoto);
END

--COMPROBAR QUE FUNCIONE
INSERT INTO VOTOS VALUES ('R01', 2, 20, '2021-12-09');
SELECT * FROM VOTOS;
SELECT * FROM PARTICIPANTES_CON_VOTOS;