/*
PRACTICA 2
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 23/11/21
DESCRIPCION: CREAR UN PROCEDIMIENTO ALMACENADO PARA ACTUALIZAR PRECIOS Y AUMENTAR UN 5%
*/

--PONER EN USO LA BD
USE NORTHWIND;

--CREAR EL PROCEDIMIENTO ALMACENADO DE sp_actualiza_precios
CREATE PROC sp_actualiza_precios
AS
BEGIN
	UPDATE Products SET UnitPrice = (UnitPrice * 1.05)
	RETURN
END

SELECT * FROM Products;

--EJECUTAR EL PROCEDIMIENTO
EXEC sp_actualiza_precios;