
-- PONER EN USO LA BD
USE SUPER

-- 1. INSERTATE COMO TRABAJADOR CON EL CARGO DE "CAJERO"
INSERT INTO TRABAJADOR
VALUES
('JESUS','CAJERO',2500)

SELECT * FROM TRABAJADOR

--2. AHORA CON UNA TRANSACCIÓN INSERTA A 2 PERSONAS MÁS QUE SEAN CAJEROS IGUALMENTE
BEGIN TRAN 
INSERT INTO TRABAJADOR VALUES('KEI', 'CAJERO', 1500)
INSERT INTO TRABAJADOR VALUES('ROXY', 'CAJERO', 1500)

SELECT * FROM TRABAJADOR

--3. SELECCIONA EL ROLLBACK PARA CANCELAR LA TRANSACCIÓN Y VERIFÍCALO
ROLLBACK 

SELECT * FROM TRABAJADOR

--4. CON UNA TRANSACCIÓN INSERTA UN PRODUCTO
BEGIN TRAN 
INSERT INTO PRODUCTOS VALUES('GANSITO', 'Pan relleno de chocolate', 12)

SELECT * FROM PRODUCTOS

--5. PARA CONFIRMAR LA TRANSACCIÓN UTILIZA EL COMMIT
COMMIT 

SELECT * FROM PRODUCTOS

--6. AHORA INTENTA DESHACER LA TRANSACCIÓN CON EL ROLLBACK. VERIFICA QUE NO HAYA FUNCIONADO
ROLLBACK 

SELECT * FROM PRODUCTOS

--7. HAZ UNA TRANSACCIÓN AGREGANDO UNA NUEVA VENTA CON LA FECHA DEL 2021-11-20 Y SU DETALLE DE VENTA, PERO QUE ESTE ÚLTIMO TENGA UN ID INEXSISTENTE
BEGIN TRAN 
INSERT INTO VENTAS VALUES('2021-11-20')
INSERT INTO DETALLES_VENTAS VALUES(6, 1, 2, 26)

--8. VERIFICA QUE LA VENTA FUE REGISTRADO PERO LOS DETALLES NO Y BORRA LA VENTA HECHA ANTERIORMENTE

SELECT * FROM VENTAS
SELECT * FROM DETALLES_VENTAS

ROLLBACK 

--9. VUELVE A HACER LA TRANSACCIÓN ANTERIOR PERO AHORA USANDO UN IF PARA QUE NO SE REALICE LA TRANSACCIÓN SI HAY UN ERROR
DECLARE @ERROR INT

BEGIN TRAN
INSERT INTO VENTAS VALUES('2021-11-20')
INSERT INTO DETALLES_VENTAS VALUES(8, 1, 2, 26)

SET @ERROR = @@ERROR

IF(@ERROR <> 0)
BEGIN
ROLLBACK TRAN
PRINT 'ERROR!!!! NO SE PUDO INSERTAR EL REGISTRO'
END

ELSE
COMMIT

SELECT * FROM VENTAS
SELECT * FROM DETALLES_VENTAS

--10. AGREGA CON PRINT UN MENSAJE DE ERROR AL IF QUE DIGA "ERROR EN LA TRANSACCIÓN"
DECLARE @ERROR INT

BEGIN TRAN
INSERT INTO VENTAS VALUES('2021-11-20')
INSERT INTO DETALLES_VENTAS VALUES(10, 1, 2, 26)

SET @ERROR = @@ERROR

IF(@ERROR <> 0)
BEGIN
ROLLBACK TRAN
PRINT 'ERROR EN LA TRANSACCIÓN'
END

ELSE
COMMIT

SELECT * FROM VENTAS
SELECT * FROM DETALLES_VENTAS

--11. POR ÚLTIMO MODIFICA LA INSERCIÓN DE DETALLES_VENTAS PARA QUE TODO ESTÉ CORRECTO
DECLARE @ERROR INT

BEGIN TRAN
INSERT INTO VENTAS VALUES('2021-11-20')
INSERT INTO DETALLES_VENTAS VALUES(6, 1, 2, 26)

SET @ERROR = @@ERROR

IF(@ERROR <> 0)
BEGIN
ROLLBACK TRAN
PRINT 'ERROR EN LA TRANSACCIÓN'
END

ELSE
COMMIT

--12. REVISA QUE EFECTIVAMENTE SE HAYA REGISTRADO LA VENTA Y SUS DETALLES

SELECT * FROM VENTAS
SELECT * FROM DETALLES_VENTAS

--13. INTENTA HACER UN ROLLBACK PARA VERIFICAR QUE EL COMMIT SE HAYA EFECTUADO CORRECTAMENTE
ROLLBACK

--14. HAZ UNA TRANSACCIÓN ACTUALIZANDO TU NOMBRE Y CAMBIANDO TU SUELDO A 9000
BEGIN TRAN
UPDATE TRABAJADOR SET TRABAJADOR.nombre_tra = 'ALBERTO'
WHERE id_tra = 5
UPDATE TRABAJADOR SET TRABAJADOR.sueldo = 9000
WHERE id_tra = 5

--15. UTILIZA EL COMMIT Y VERIFICA QUE SE HAYAN HECHO LOS CAMBIOS
COMMIT

SELECT * FROM TRABAJADOR