
--PONER EN USO LA BD
USE DULCERIA

--1.- GENERAR EL DIAGRAMA CON LA CLASE PERSONALIZADA Y ANALIZARLO
-- NO SE PUEDE HACER 

--2.- CREAR UN LOGIN Y USUARIO LLAMADO ADMINISTRADOR Y UN ROL A NIVEL SERVIDOR LLAMADO R_ADMIN
CREATE LOGIN ADMINISTRADOR WITH PASSWORD = '123';
CREATE USER ADMINISTRADOR FOR LOGIN ADMINISTRADOR;

CREATE SERVER ROLE R_ADMIN;

--3.- DAR PERMISOS AL ROL R_ADMIN DE HACER INSERCIONES MASIVAS, Y QUE PUEDA CREAR BASES DE DATOS	 

ALTER SERVER ROLE BULKADMIN ADD MEMBER R_ADMIN;
ALTER SERVER ROLE DBCREATOR ADD MEMBER R_ADMIN;


--4.- ASIGNA EL USUARIO ADMINISTRADOR EL ROL CREADO Y COMPRUEBA QUE SOLO PUEDA REALIZAR ESTAS ACCIONES

ALTER SERVER ROLE R_ADMIN ADD MEMBER ADMINISTRADOR;

--5.- ELIMINAR EL ROL, USARIO Y LOGIN PERTENECIENTE AL ADMINISTRADOR
DROP USER ADMINISTRADOR;
ALTER SERVER ROLE R_ADMIN DROP MEMBER ADMINISTRADOR;
DROP SERVER ROLE R_ADMIN;
DROP LOGIN ADMINISTRADOR;

--6.- CREAR UN LOGIN QUE SE LLAME GERENTE CON CONTRASEÑA 1234
CREATE LOGIN GERENTE WITH PASSWORD = '1234'

--7.- CREAR EL USUARIO PARA EL LOGIN ANTERIOR
CREATE USER GERENTE FOR LOGIN GERENTE;

--8.- CREAR UN ROL LLAMADO GERENTE Y PONERLE EL ROL PREDEFINIDO DB_OWNER
CREATE ROLE R_GERENTE;
ALTER ROLE DB_OWNER ADD MEMBER R_GERENTE;

--9.- CREAR UN USUARIO Y LOGIN LLAMADO PROVEEDOR Y UN ROL LLAMADO R_PROVEEDOR

CREATE LOGIN PROVEEDOR WITH PASSWORD = '123'
CREATE USER PROVEEDOR FOR LOGIN PROVEEDOR;
CREATE ROLE R_PROVEEDOR;
--10.- PERMITIR SOLAMENTE AL ROL R_PROVEEDOR LA LECTURA DE LA VISTA V_CANTIDADES * AGREGA AL ROL R_PROVEEDOR AL USUARIO PROVEEDOR Y VERIFICA QUE ESTE PUEDA LEER LA VISTA
	ALTER ROLE R_PROVEEDOR ADD MEMBER PROVEEDOR;

	GRANT SELECT ON V_CANTIDADES TO R_PROVEEDOR;

--11.- CREAR UN USUARIO Y LOGIN LLAMADO EMPLEADO Y UN ROL LLAMADO R_EMPLEADO
CREATE LOGIN EMPLEADO WITH PASSWORD = '123'
CREATE USER EMPLEADO FOR LOGIN EMPLEADO
CREATE ROLE R_EMPLEADO;
--12.- DAR PERMISO DE INSERTAR, ACTUALIZAR, ELIMINAR Y SELECCIONAR SOBRE LA TABLA PEDIDO AL ROL R_EMPLEADO
 GRANT INSERT, UPDATE, DELETE, SELECT ON PEDIDO TO R_EMPLEADO;
--13.- AÑADIR AL ROL R_EMPLEADO EL PERMISO DEL PUNTO 8 (DB_OWNER)
ALTER ROLE DB_OWNER ADD MEMBER R_EMPLEADO
--14.- CREA UN LOGIN NUEVO CON CONTRAEÑA 1234 Y UN USUARIO
CREATE LOGIN FABIAN WITH PASSWORD = '123';
CREATE USER FABIAN FOR LOGIN FABIAN;
--15.- CREA UN ROL DE APLICACION CON NOMBRE APP_READERWRITER Y CONTRASEÑA 123 EL CUAL TENDRÁ EL ROL FIJO DE DB_DATAREADER Y DB_DATAWRITER SOBRE LA BASE DE DATOS *INICIA SESION CON EL NUEVO USUARIO Y COMPROBAR QUE ESTE USUARIO NO PUEDE REALIZAR NINGUNA ACCION SOBRE LA BASE DE DATOS

	CREATE APPLICATION ROLE APP_READERWRITER WITH PASSWORD = '123'
	ALTER ROLE DB_DATAREADER ADD MEMBER APP_READERWRITER;
	ALTER ROLE DB_DATAWRITER ADD MEMBER APP_READERWRITER;

--16.- INICIAR SESION CON EL NUEVO USUARIO Y ACTIVAR EL ROL DE APLICACION CREADO ANTERIORMENTE

EXEC sp_setapprole 'APP_READERWRITER', '123';

SELECT * FROM ALMACEN;

--17. HACER DOS INSERCIONES EN LA TABLA PEDIDO

INSERT INTO PEDIDO VALUES (1,'DOMICILIO','2021-11-10',535), (1,'EN TIENDA','2021-11-20',125)

SELECT * FROM PEDIDO;

--18.- ELIMINAR A TODOS LOS ROLES, USUARIOS Y LOGINS CREADOS ANTERIORMENTE

DROP USER EMPLEADO;
DROP USER FABIAN;
DROP USER GERENTE;
DROP USER PROVEEDOR;

DROP ROLE R_EMPLEADO;
DROP ROLE R_GERENTE;
DROP ROLE R_PROVEEDOR;

DROP APPLICATION ROLE APP_READERWRITER;

DROP LOGIN EMPLEADO;
DROP LOGIN FABIAN;
DROP LOGIN GERENTE;
DROP LOGIN PROVEEDOR;