/**
PRACTICA 3
AUTOR: INZUNSA DIAZ CESAR ALEAJANDRO
NO. CONTROL: 19400595
FECHA: 16/09/2021
DESCRIPCION: CREA UNA BASE DE DATOS PARA UNA TIENDA DE ABARROTES EN DONDE SE PUEDAN REGISTRAR SU INVENTARIO Y SUS VENTAS.
DEBERA UTILIZAR TODOS LOS PARAMETROS DE CREACION DE LA BD DE ACUERDO A LAS INDICACIONES.
*/

--CREAR BASE DE DATOS
CREATE DATABASE TIENDAABARROTES
ON PRIMARY
(
NAME = 'TIENDAABARROTES_DATA',
FILENAME = 'C:\TBD2021\U1/TIENDAABARROTES.MDF',
SIZE = 10MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 10%
)
LOG ON
(
NAME = 'TIENDAABARROTES_LOG',
FILENAME = 'C:\TBD2021\U1/TIENDAABARROTES.LDF',
SIZE = 10MB,
MAXSIZE = UNLIMITED
);

-- PONER EN USO LA BD
USE TIENDAABARROTES;

-- CREAR TABLAS

--CREAR TABLA DE ARTICULOS
CREATE TABLE ARTICULOS
(
idArticulo TINYINT NOT NULL IDENTITY(1,1),
nombre VARCHAR(30),
descripcion VARCHAR(400),
precio SMALLMONEY,
stock TINYINT,
idCategoria TINYINT,
idProveedor TINYINT
);

--CREAR TABLA DE CATEGORIAS DE PRODUCTOS
CREATE TABLE CATEGORIASPRODUCTOS
(
idCategoria TINYINT NOT NULL IDENTITY(1,1),
nombre VARCHAR(30),
descripcion VARCHAR(400)
)

--CREAR TABLA DE VENTAS
CREATE TABLE VENTAS
(
idVenta TINYINT NOT NULL IDENTITY(1,1),
idArticulo TINYINT,
cantidad TINYINT,
precioTotal SMALLMONEY,
fechaVenta DATETIME,
idEmpleado TINYINT
);

--CREAR TABLA DE PROVEEDORES
CREATE TABLE PROVEEDORES
(
idProveedor TINYINT NOT NULL IDENTITY(1,1),
nombre VARCHAR(30),
RFC VARCHAR(12),
ciudad VARCHAR(30),
calle VARCHAR(30),
numero TINYINT
);

--CREAR TABLA DE EMPLEADOS
CREATE TABLE EMPLEADOS
(
idEmpleado TINYINT NOT NULL IDENTITY(1,1),
nombre VARCHAR(30),
apellidoPaterno VARCHAR(30),
apellidoMaterno VARCHAR(30),
cp VARCHAR(5),
numTelefono VARCHAR(10),
ciudad VARCHAR(30),
calle VARCHAR(30),
numero VARCHAR(10)
);

-- CREAR LLAVES PRIMARIAS

--CREAR LLAVE PRIMARIA DE ARTICULOS
ALTER TABLE ARTICULOS
ADD CONSTRAINT PK_ARTICULOS
PRIMARY KEY (idArticulo);

--CREAR LLAVE PRIMARIA DE CATEGORIA DE PRODUCTOS
ALTER TABLE CATEGORIASPRODUCTOS
ADD CONSTRAINT PK_CATEGORIAPRODUCTO
PRIMARY KEY (idCategoria);

--CREAR LLAVE PRIMARIA DE DE VENTAS
ALTER TABLE VENTAS
ADD CONSTRAINT PK_VENTAS
PRIMARY KEY (idVenta);

--CREAR LLAVE PRIMARIA DE PROVEEDORES
ALTER TABLE PROVEEDORES
ADD CONSTRAINT PK_PROVEEDORES
PRIMARY KEY (idProveedor);

--CREAR LLAVE PRIMARIA DE EMPLEADOS
ALTER TABLE EMPLEADOS
ADD CONSTRAINT PK_EMPLEADOS
PRIMARY KEY (idEmpleado);

-- CREAR LLAVES FORANEAS

--CREAR LLAVE FORANEA DE ARTICULOS CON CATEGORIAS
ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_ARTICULOS_CATEGORIASPRODUCTOS
FOREIGN KEY (idCategoria)
REFERENCES CATEGORIASPRODUCTOS (idCategoria);

----CREAR LLAVE FORANEA DE ARTICULOS CON PROVEEDORES
ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_ARTICULOS_PROVEEDORES
FOREIGN KEY (idProveedor)
REFERENCES PROVEEDORES (idProveedor);

--CREAR LLAVE FORANEA DE VENTAS CON ARTICULOS
ALTER TABLE VENTAS
ADD CONSTRAINT FK_VENTAS_ARTICULOS
FOREIGN KEY (idArticulo)
REFERENCES ARTICULOS (idArticulo);

--CREAR LLAVE FORANEA DE VENTAS CON EMPLEADOS
ALTER TABLE VENTAS
ADD CONSTRAINT FK_VENTAS_EMPLEADOS
FOREIGN KEY (idEmpleado)
REFERENCES EMPLEADOS (idEmpleado);

-- AGREGAR RESTRICCIONES DE CHECK

--CREAR RESTRICCION DE CHECK DE ARTICULOS
ALTER TABLE ARTICULOS
ADD CONSTRAINT CK_ARTICULOS_STOCK
CHECK (stock BETWEEN 0 AND 30);

--CREAR RESTRICCION DE CHECK DE ARTICULOS
ALTER TABLE ARTICULOS
ADD CONSTRAINT CK_ARTICULOS_PRECIO
CHECK (precio > 0);

--CREAR RESTRICCION DE CHECK DE VENTAS
ALTER TABLE VENTAS
ADD CONSTRAINT CK_VENTAS_PRECIOTOTAL
CHECK (precioTotal > 0);

-- AGREGAR CONSTRAINT DE DEFAULT

--CREAR RESTRICCION DE DEFAULT DE VENTAS
ALTER TABLE VENTAS
ADD CONSTRAINT DF_VENTAS_FECHA
DEFAULT GETDATE() FOR fechaVenta;

--CREAR RESTRICCION DE CHECK DE ARTICULOS
ALTER TABLE ARTICULOS
ADD CONSTRAINT DF_ARTICULOS_NOMBRE
DEFAULT 'item'
FOR nombre;