/**
PRACTICA 4
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 29/09/2021
DESCRIPCION: REALIZAR UNA BASE DE DATOS PARA CONTROLAR EL MOVIMIENTO DE UNA BIBLIOTECA.
LA BASE DE DATOS ESTARÁ COMPUESTA POR TRES TABLAS: SOCIOS, LIBROS Y PRÉSTAMOS.
**/

--CREAR BASE DE DATOS
CREATE DATABASE BIBLIOTECA
ON PRIMARY
(
NAME = 'BIBLIOTECA.MDF',
FILENAME = 'C:\TBD2021\U1\BIBLIOTECA.MDF'
)
LOG ON
(
NAME = 'BIBLIOTECA.LDF',
FILENAME = 'C:\TBD2021\U1\BIBLIOTECA.LDF'
);

--PONER EN USO LA BASE DE DATOS
USE BIBLIOTECA;

--CREAR TABLA SOCIOS
CREATE TABLE SOCIOS
(
Nombre VARCHAR(20) NOT NULL,
Direccion  VARCHAR(60),
[Numero de telefono] VARCHAR(15),
[Fecha de incripcion] SMALLDATETIME,
[No. De Socio] TINYINT NOT NULL IDENTITY(1,1),
CONSTRAINT FK_SOCIOS_IDSOCIO PRIMARY KEY ([No. De Socio]) 
);

--CREAR TABLA LIBROS
CREATE TABLE LIBROS
(
Titulo VARCHAR(50),
Autor1 VARCHAR(50),
Autor2 VARCHAR(50),
Autor3 VARCHAR(50),
[Fecha de Edicion] SMALLDATETIME,
[No. De Libro] INT NOT NULL  IDENTITY(1,1),
CONSTRAINT FK_LIBROS_LIBROID PRIMARY KEY ([No. De Libro])
);

--CREAR TABLA PRESTAMOS
CREATE TABLE PRESTAMOS
(
[Fecha de prestamo] SMALLDATETIME,
[Fecha de entrega] SMALLDATETIME,
[No. De Socio] TINYINT,
[No. De libro] INT,
[Id. Prestamo]  INT NOT NULL IDENTITY(1,1),
CONSTRAINT PK_PRESAMOS_IDPRESTAMOS PRIMARY KEY ([Id. Prestamo]),
CONSTRAINT FK_PRESTAMOS_LIBROS FOREIGN KEY([No. De libro]) REFERENCES LIBROS([No. De libro])
);

--CREAR LLAVE FORANEA DE SOCIOS EN LA TABLA PRESTAMOS
ALTER TABLE PRESTAMOS
ADD CONSTRAINT FK_PRESTAMOS_SOCIOS
FOREIGN KEY ([No. De Socio])
REFERENCES SOCIOS([No. De Socio])

--AGREGAR UN CONSTRAINT DE DEFAULT A LA FECHA DE PRÉSTAMO QUE SEA LA FECHA DE SISTEMA
ALTER TABLE PRESTAMOS
ADD CONSTRAINT DF_PRESTAMOS_FECHADEPRESTAMO
DEFAULT getdate()
FOR [Fecha de prestamo];

--AGREGAR UN CONSTRAINT DE CHECK AL CAMPO DE FECHA DE ENTREGA NO PODRÁ SER MENOR A LA FECHA DE PRÉSTAMO
ALTER TABLE PRESTAMOS
ADD CONSTRAINT CK_PRESTAMOS_FECHAENTREGA
CHECK ([Fecha de entrega] > [Fecha de prestamo]);

--AGREGAR UN CAMPO A LA TABLA PRESTAMOS LLAMADO OBSERVACIONES DE 60 CARACTERES.
ALTER TABLE PRESTAMOS
ADD Observaciones VARCHAR(60);

--AGREGAR UN CONSTRAINT DE DEFAULT AL NUMERO TELEFONICO EL VALOR USTED LO DEFINIRA.
ALTER TABLE SOCIOS
ADD CONSTRAINT DF_SOCIOS_TELEFONO
DEFAULT '004961716988920'
FOR [Numero de telefono];