/**
PRACTICA 5
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 29/09/2021
DESCRIPCION: EL CANAL DE TELEVISION DE PAGA EL GOURMET, TIENE UNA SERIE DE PROGRAMAS ESTELARILZADOS
POR DIFERENTES CHEFS DE TALLA INTERNACIONAL, LOS CUALES HAN CREADO RECETAS DE DIFERENTES TIPOS O CATEGORIAS.
**/

--CREAR BASE DE DATOS
CREATE DATABASE ELGOURMET
ON PRIMARY
(
NAME = 'ELGOURMET.MDF',
FILENAME = 'C:\TBD2021\U1\ELGOURMET.MDF'
)
LOG ON
(
NAME = 'ELGOURMET.LDF',
FILENAME = 'C:\TBD2021\U1\ELGOURMET.LDF'
);

--PONER EN USO LA BASE DE DATOS
USE ELGOURMET;

--CREAR LA TABLA CATEGORIA
CREATE TABLE Categoria
(
IDCategoria SMALLINT PRIMARY KEY IDENTITY(1,1),
CategoriaDescripcion VARCHAR(50)
);

--CREAR TABLA CHEF
CREATE TABLE Chef
(
IDChef TINYINT PRIMARY KEY IDENTITY(1,1),
ChefNombre VARCHAR(70),
ChefEspecialidad VARCHAR(30)
);

--CREAR TABLA INGREDIENTE
CREATE TABLE Ingrediente
(
IDIngrediente INT PRIMARY KEY IDENTITY(1,1),
IngNombre VARCHAR(50),
IngDescripcion VARCHAR(200)
);

--CREAR TABLA RECETA
CREATE TABLE Receta
(
IDReceta INT PRIMARY KEY IDENTITY(1,1),
RecetaNombre VARCHAR(50),
RecetaDescripcion VARCHAR(200),
RecetaCosto MONEY,
RecetaModoPreparacion NVARCHAR(MAX),
IDChef TINYINT REFERENCES Chef(IDChef),
IDCategoria SMALLINT REFERENCES Categoria(IDCategoria)
);

--CREAR TABLA DETALLE DE RECETA
CREATE TABLE DetReceta
(
IDDetReceta INT PRIMARY KEY IDENTITY(1,1),
IDIngrediente INT REFERENCES Ingrediente(IDIngrediente),
IDReceta INT REFERENCES Receta(IDReceta)
);

--CREAR CONSTRAINT DE DEFAUL EN RecetaDescripción DE "ES UNA RECETA DELICIOSA"
ALTER TABLE Receta
ADD CONSTRAINT DF_RECETA_DESCRIPCION
DEFAULT 'ES UNA RECETA DELICIOSA'
FOR RecetaDescripcion;

--CREAR CONSTRAINT DE CHECK PARA EL COSTO DE LA RECETA QUE SEAN MAYOR QUE 100 PERO MENOR DE 1000
ALTER TABLE Receta
ADD CONSTRAINT CK_RECETA_COSTO
CHECK (RecetaCosto BETWEEN 100 AND 1000);

--CREAR CONSTRAINT DE CHECK PARA LA ESPECIALIDAD DEL CHEF, LISTA DE ESPECIALIDADES DEL CHEF
ALTER TABLE Chef
ADD CONSTRAINT CK_CHEF_ESPECIALIDAD
CHECK (ChefEspecialidad IN ('Chef Saucier','Chef Poissonnier','Chef Rotisseur', 'Chef Grillardin', 'Chef Friturier'));