/**
PRACTICA 2
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 13/09/2021
DESCRIPCION: IMPLEMENTAR UNA BD PARA EL CONTROL DE UN KINDER (ASISTENCIAS Y REGISTROS DE ALUMNOS)
**/

--CREAR BASE DE DATOS
CREATE DATABASE KINDERGARDEN
ON PRIMARY
(
NAME = 'KINDERGARDEN.MDF',
FILENAME = 'C:\TBD2021\U1\KINDERGARDEN.MDF',
SIZE = 10MB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 10%
)
LOG ON
(
NAME = 'KINDERGARDEN.LDF',
FILENAME = 'C:\TBD2021\U1\KINDERGARDEN.LDF',
SIZE = 10MB,
MAXSIZE = UNLIMITED
);

--PONER EN USO LA BD
USE KINDERGARDEN;

--CREAR TABLAS

--CREAR TABLA DE MAESTROS ENCARGADOS
CREATE TABLE MAESTROS
(
idMaestro TINYINT NOT NULL IDENTITY(1,1),
nombre VARCHAR(30),
apellidoPaterno VARCHAR(30),
apellidoMaterno VARCHAR(30),
fechaIngreso DATE,
edad TINYINT,
grado VARCHAR(60),
email VARCHAR(150),
domicilio VARCHAR(100),
telefono CHAR(10)
);

--CREAR TABLA GRUPOS
CREATE TABLE GRUPOS
(
idGrupo TINYINT NOT NULL,
grado VARCHAR(15),
grupo CHAR(1),
idMaestro TINYINT,
capacidad TINYINT
);

--CREAR TABLA ALUMNOS
CREATE TABLE ALUMNOS
(
idAlumno SMALLINT NOT NULL,
nombre VARCHAR(30),
apellidoPaterno VARCHAR(30),
apellidoMaterno VARCHAR(30),
idGrupo TINYINT,
edad TINYINT,
tutor VARCHAR(100),
telefonoTutor CHAR(10),
fechaNacimiento DATE
);

--CREAR TABLA CONTROL DE ASISTENCIA
CREATE TABLE CONTROLASISTENCIA
(
idControl INT NOT NULL IDENTITY (1,1),
tipo VARCHAR(10),
horaRegistro TIME,
fechaRegistro DATE,
idAlumno SMALLINT
);

--CREAR TABLA REPORTES
CREATE TABLE REPORTES
(
idReporte INT NOT NULL IDENTITY(1,1),
idTipo TINYINT,
horaReporte TIME,
fechaReporte DATE,
observaciones VARCHAR(MAX),
idAlumno SMALLINT,
idMaestro TINYINT
);

--CREAR TABLA TIPOS DE REPORTE
CREATE TABLE TIPOREPORTE
(
idTipo TINYINT NOT NULL,
nombreTipo VARCHAR(20),
descripcion VARCHAR(400)
);

--CREAR LLAVES PRIMARIAS

--CREAR LLAVE PRIMARIA DE MAESTROS
ALTER TABLE MAESTROS
ADD CONSTRAINT PK_MAESTROS
PRIMARY KEY (idMaestro);

--CREAR LLAVE PRIMARIA DE GRUPOS
ALTER TABLE GRUPOS
ADD CONSTRAINT PK_GRUPOS
PRIMARY KEY (idGrupo);

--CREAR LLAVE PRIMARIA DE ALUMNOS
ALTER TABLE ALUMNOS
ADD CONSTRAINT PK_ALUMNOS
PRIMARY KEY (idAlumno);

--CREAR LLAVE PRIMARIA DE CONTROL DE ASISTENCIA
ALTER TABLE CONTROLASISTENCIA
ADD CONSTRAINT PK_CONTROLASISTENCIA
PRIMARY KEY (idControl);

--CREAR LLAVE PRIMARIA DE REPORTES
ALTER TABLE REPORTES
ADD CONSTRAINT PK_REPORTES
PRIMARY KEY (idReporte);

--CREAR LLAVE PRIMARIA DE TIPO DE REPORTE
ALTER TABLE TIPOREPORTE
ADD CONSTRAINT PK_TIPOREPORTE
PRIMARY KEY (idTipo);

---AGREGAR LAS LLAVES FORANEAS

--CREAR LLAVE FORANEA DE ALUMNOS CON GRUPOS
ALTER TABLE ALUMNOS
ADD CONSTRAINT FK_ALUMNOS_GRUPOS
FOREIGN KEY (idGrupo)
REFERENCES GRUPOS (idGrupo);

--CREAR LLAVE FORANEA DE GRUPOS CON MAESTROS
ALTER TABLE GRUPOS
ADD CONSTRAINT FK_GRUPOS_MAESTROS
FOREIGN KEY (idMaestro)
REFERENCES MAESTROS (idMaestro);

--CREAR LLAVE FORANEA DE CONTROL DE ASISTENCIA CON ALUMNOS
ALTER TABLE CONTROLASISTENCIA
ADD CONSTRAINT FK_CONTROLASISTENCIA_ALUMNOS
FOREIGN KEY (idAlumno)
REFERENCES ALUMNOS (idAlumno);

--CREAR LLAVE FORANEA DE REPORTES CON TIPO DE REPORTE
ALTER TABLE REPORTES
ADD CONSTRAINT FK_REPORTES_TIPOREPORTE
FOREIGN KEY (idTipo)
REFERENCES TIPOREPORTE (idTipo);

--CREAR LLAVE FORANEA DE REPORTES CON ALUMNOS
ALTER TABLE REPORTES
ADD CONSTRAINT FK_REPORTES_ALUMNOS
FOREIGN KEY (idAlumno)
REFERENCES ALUMNOS (idAlumno);

--CREAR LLAVE FORANEA DE REPORTES CON MAESTROS
ALTER TABLE REPORTES
ADD CONSTRAINT FK_REPORTES_MAESTROS
FOREIGN KEY (idMaestro)
REFERENCES MAESTROS (idMaestro);

-- AGREGAR RESTRICCIONES DE CHECK

--CREAR RESTRICCION DE CHECK DE ALUMNOS EN EDAD
ALTER TABLE ALUMNOS
ADD CONSTRAINT CK_ALUMNOS
CHECK (edad BETWEEN 3 AND 6);

--CREAR RESTRICCION DE CHECK DE CONTROL DE ASISTENCIA EN TIPO
ALTER TABLE CONTROLASISTENCIA
ADD CONSTRAINT CK_CONTROLASISTENCIA_TIP
CHECK (tipo IN ('ENTRANDA','SALIDA'));

--CREAR RESTRICCION DE CHECK DE GRUPOS EN CAPACIDAD
ALTER TABLE GRUPOS
ADD CONSTRAINT CK_GRUPOS_CAPACIDAD
CHECK (capacidad >= 5 AND capacidad <= 30);

-- AGREGAR CONSTRAINT DE DEFAULT

--CREAR RESTRICCION DE DEFAULT DE COONTROL DE ASISTENCIA EN FECHA DE REGISTRO
ALTER TABLE CONTROLASISTENCIA
ADD CONSTRAINT DF_CONTROLASISTENCIA_FECHA
DEFAULT GETDATE()
FOR fechaRegistro;