/**
PRACTICA 8
AUTOR: INZUNSA DIAZ CESAR ALEJANDRO
NO. CONTROL: 19400595
FECHA: 30/09/2021
DESCRIPCION: CREAR UNA BD DE UNA HOTEL PARA LLEVAR EL CONTROL Y REGISTRO DE LAS RESERVAS DE LAS
HABITACIONES Y SERVICIOS.
**/

CREATE DATABASE ReservacionesHotel
ON PRIMARY
(
NAME = 'ReservacionesHotel.MDF',
FILENAME = 'C:\TBD2021\U1\ReservacionesHotel.MDF'
)
LOG ON
(
NAME = 'ReservacionesHotel.LDF',
FILENAME = 'C:\TBD2021\U1\ReservacionesHotel.LDF'
);

--PONER EN USO LA BASE DE DATOS
USE ReservacionesHotel;

--CREAR TABLA DE HABITACION
CREATE TABLE HABITACION(
idHabitacion INT NOT NULL,
noCamas INT,
precio MONEY
);


--CREAR TABLA DE CLIENTE
CREATE TABLE CLIENTE(
idCliente INT NOT NULL,
nombreCliente VARCHAR(50),
apellidoCliente VARCHAR(50),
telefonoCliente VARCHAR(10),
noTarjeta VARCHAR(16)
);


--CREAR TABLA DE RESERVA
CREATE TABLE RESERVA_HABITACION(
idReserva INT NOT NULL,
idCliente INT NOT NULL,
idHabitacion INT NOT NULL,
fechaEntrada DATE,
fechaSalida DATE
);


--CREAR TABLA DE SERVICIOS
CREATE TABLE SERVICIOS(
idServicio INT NOT NULL,
nombreServicio VARCHAR(50),
descripcionServicio VARCHAR(300)
);


--CREAR TABLA DE RESERVA SERVICIO
CREATE TABLE RESERVA_SERVICIO(
idServicio INT NOT NULL,
idReserva INT NOT NULL
);


--AGREGAR LLAVES PRIMARIAS A LAS TABLAS

--HABITACION
ALTER TABLE HABITACION
ADD CONSTRAINT PK_HABITACION
PRIMARY KEY (idHabitacion);


--CLIENTE
ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (idCliente);


--SERVICIOS
ALTER TABLE SERVICIOS
ADD CONSTRAINT PK_SERVICIOS
PRIMARY KEY (idServicio);


--RESERVA_HABITACION
ALTER TABLE RESERVA_HABITACION
ADD CONSTRAINT PK_RESERVA_HABITACION
PRIMARY KEY (idReserva);


--RESERVA_SERVICIO
ALTER TABLE RESERVA_SERVICIO
ADD CONSTRAINT PK_RESERVA_SERVICIO
PRIMARY KEY (idServicio, idReserva);


--CREAR LLAVES FORANEAS A LAS TABLAS

--RESERVA_HABITACION
ALTER TABLE RESERVA_HABITACION ADD
CONSTRAINT FK_CLIENTE_RESERVAHABITACION FOREIGN KEY (idCliente) REFERENCES CLIENTE (idCliente),
CONSTRAINT FK_HABITACION_RESERVAHABITACION FOREIGN KEY (idHabitacion) REFERENCES HABITACION (idHabitacion);


--RESERVA_SERVICIO
ALTER TABLE RESERVA_SERVICIO ADD
CONSTRAINT FK_RESERVAHABITACION_RESERVASERVICIO  FOREIGN KEY (idReserva) REFERENCES RESERVA_HABITACION (idReserva),
CONSTRAINT FK_SERVICIO_RESERVASERVICIO FOREIGN KEY (idServicio) REFERENCES SERVICIOS (idServicio);


--AGREGAR RESTRICCIONES

--HABITACION RESTRICCION DE CHECK PARA noCamas Y precio
ALTER TABLE HABITACION ADD
CONSTRAINT CK_HABITACION_noCamas CHECK(noCamas > 0),
CONSTRAINT CK_HABITACION_precio CHECK(precio > 0);


--RESERVA_HABITACION DE DEFAULT PARA FechaEntrada
ALTER TABLE RESERVA_HABITACION
ADD CONSTRAINT DF_RESERVA_HABITACION_FechaEntrada
DEFAULT (GETDATE())
FOR FechaEntrada;

--RESERVA_HABITACION DE CHECK PARA FechaEntrada Y FechaSalida
ALTER TABLE RESERVA_HABITACION ADD
CONSTRAINT CK_RESERVA_HABITACION_FechaEntrada CHECK(FechaEntrada >= GETDATE()),
CONSTRAINT CK_RESERVA_HABITACION_FechaSalida CHECK(FechaSalida > FechaEntrada);